repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-docstring-first
    -   id: check-merge-conflict
        stages:
        - push
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: mixed-line-ending
    -   id: trailing-whitespace
-   repo: https://github.com/pycqa/flake8
    rev: "4.0.1"
    hooks:
    -   id: flake8
        args: ['--config=setup.cfg']
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
    -   id: autopep8
